version: "3.9"

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: login_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  auth-service:
    build: ./Backend/login-service/auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - ./Backend/login-service/auth-service/.env
    depends_on:
      - postgres-db
    networks:
      - app-network
    entrypoint: ["/wait-for-it.sh", "postgres-db", "5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
