name: Deploy Microservices to EC2

on:
  push:
    branches:
      - test

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push auth-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/create-customer:latest ./Backend/customer-service/create-customer
          docker push ${{ secrets.DOCKER_USERNAME }}/create-customer:latest

      - name: Build and push authorization-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/delete-customer:latest ./Backend/customer-service/delete-customer
          docker push ${{ secrets.DOCKER_USERNAME }}/delete-customer:latest

      
  deploy:
    name: Deploy Docker Containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images
    
    steps:
    
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_CUSTOMER_TEST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt update -y
            sudo apt install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker

            docker stop create-customer delete-customer  || true
            docker rm create-customer  delete-customer  || true
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/create-customer:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/delete-customer:latest 

            docker run -d -p 8003:80 --name create-customer  ${{ secrets.DOCKER_USERNAME }}/create-customer:latest
            docker run -d -p 8004:8004 --name delete-customer  ${{ secrets.DOCKER_USERNAME }}/delete-customer:latest
        #katyjoseth719
