name: Deploy Login Microservices to EC2

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST_LOGIN_TEST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo apt update -y
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

          # Crear red si no existe
          docker network create app-network || true

          # Parar y eliminar contenedores antiguos
          sudo docker stop auth-service authorization-service || true
          sudo docker rm auth-service authorization-service || true

          # Descargar imágenes
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authorization-service:latest

          # Ejecutar contenedores
          sudo docker run -d --name auth-service --network app-network -p 8001:8000 --env-file /home/ubuntu/.env-auth ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          sudo docker run -d --name authorization-service --network app-network -p 8002:8002 --env-file /home/ubuntu/.env-authorization ${{ secrets.DOCKER_USERNAME }}/authorization-service:latest
