name: Deploy Login Microservices to EC2

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push auth-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest ./Backend/login-service/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Build and push authorization-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/authorization-service:latest ./Backend/login-service/authorization-service
          docker push ${{ secrets.DOCKER_USERNAME }}/authorization-service:latest

  deploy:
    name: Deploy Auth + Authorization on EC2
    runs-on: ubuntu-latest
    needs: build_and_push_images

    steps:
    - name: Deploy auth-service to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST_AUTH_TEST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo apt update -y
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

          # Crear red si no existe
          docker network create app-network || true

          # Parar y eliminar contenedores antiguos
          sudo docker stop auth-service authorization-service || true
          sudo docker rm auth-service authorization-service || true

          # Descargar imágenes
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authorization-service:latest


          # Ejecutar contenedores
          sudo docker run -d --restart unless-stopped --name auth-service --env-file .env-auth --network app-network -p 8001:8000 ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
          sudo docker run -d --restart unless-stopped --name authorization-service --network app-network -p 8002:8002 --env-file /home/ubuntu/.env-auth ${{ secrets.DOCKER_USERNAME }}/authorization-service:latest

    